		<!--[if IE]>
			<style type="text/css" media="all">
				#rcol {
					position: absolute; 
					width: 150px; 
					top: 0px; 
					right: 0px;
					margin-top: 140px;
					background: transparent;
				}
			</style>
		<![endif]-->
		<!--[if IE 5]>
			<style type="text/css" media="all">
				#rcol {
					position: absolute; 
					width: 150px; 
					top: 0px; 
					right: 0px;
					margin-top: 148px;
					background: transparent;
				}
			</style>
		<![endif]-->
