<ul>
	<li><a href="/" title="weblog">Blog</a></li>
	<li><a href="/kontakt/" title="Hvem står bag?">Info // Kontakt</a></li>
	<li><a href="/services/" title="Public Service">Services</a></li>
	<li><a href="http://wax.verture.net/" title="Plader og CD'ere">Plader</a></li>
	<li><a href="/io/http://23hq.dk/voss" title="Glimt">23</a></li>
	<li><a href="/kolofon/" title="Tech spec">Kolofon</a></li>
	<li>
	   <form style="display:inline;" action="/do_search.php" method="get" id="search" onsubmit="if(this.q.value=='Skriv søgeord' || this.q.value=='') { alert('Du skal skrive et gyldigt søgeord først.'); this.q.select(); return false;} else { this.submit();}">
			<div style="display:inline; padding-left: 30%;">
	      <input type="text" name="q" value="Skriv søgeord" onclick="this.select()" style="width: 100px;" />
	      </div>
		</form>
	</li>
</ul>
