	<p>
		<a href="http://validator.w3.org/check/referer" title="XHTML 1.1 - og luk så de tags">XHTML 1.1</a> // 
		<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://<?=$domain_name;?>/css/prik.css" title="CSS 2.0 - fordi det ikke er 1993 længere">CSS 2.0</a> // 
		<a title="RSS 2.0 feed af '<?=$blog_title;?>'" href="http://<?=$domain_name;?>/rssfeed.xml">RSS 2.0</a> // 
		<a title="Creative Commons Licensed" href="http://creativecommons.org/licenses/by-nc-sa/1.0/">CC-Licensed</a> // 
		<a href="http://geourl.org/near/?p=http://verture.net/" title="GeoURL">GeoURL</a> // 
		<a href="http://del.icio.us/voss" title="Mine del.icio.us-links">del.icio.us</a>
	</p>